# https://rocket.rs/v0.4/guide/configuration/

[development]
log = "normal"
address = "localhost"
port = 7070
workers = 2

[staging]
log = "normal"
address = "0.0.0.0"
port = 4242
workers = 2

[production]
log = "critical"
address = "0.0.0.0"
port = 80
workers = 2
